# SPDX-License-Identifier: ISC
---
name: lint

on:
  pull_request:
    paths:
      - .github/workflows/lint.yml
      - cmd/**/*.go
      - lib/**/*.go
      - src/**/*.go
      - cugo.go
      - go.mod
      - go.sum
  push:
    paths:
      - .github/workflows/lint.yml
      - cmd/**/*.go
      - lib/**/*.go
      - src/**/*.go
      - cugo.go
      - go.mod
      - go.sum
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18.1"

      - name: go mod verify
        run: go mod verify

      - name: go vet
        run: go vet -v

      - name: go test
        run: go test -v -bench=^$ -run=. ./...

      - name: go bench
        run: go test -v -bench=. -benchmem -run=^$ ./...
